on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      #modifier lutilisateur courant
    - name: modifier lutilisateur courant
      run: runas /user:GMT\flemelle "whoami"
      shell: cmd
    
    - name: run iristerm
      run: |
        C:\InterSystems\Cache\bin\iristerm.exe
      shell: pwsh


