on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Spécifie ici le runner auto-hébergé
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
      - name: Display current directory
        run: |
          echo Current directory is: %cd%
        shell: cmd  
      - name: Run iristerm script IMPORT
        run: |
           "C:\InterSystems\Cache\bin\iristerm.exe" /console=cn_iptcp:127.0.0.1[23] "C:\serveurtest\SERVEUR-TEST\IRISImport.scr" > output.log 2>&1
           type output.log
        shell: cmd
