on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Spécifie ici le runner auto-hébergé

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Qui est là
      run: whoami
      shell: cmd

    - name: Run iristerm
      run: |
        C:\InterSystems\Cache\bin\iristerm.exe
      shell: cmd