name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List root directory contents
      run: dir C:\
      shell: cmd

    - name: List InterSystems directory contents
      run: dir C:\InterSystems
      shell: cmd

    - name: List Cache directory contents
      run: dir C:\InterSystems\Cache
      shell: cmd

    - name: Verify iristerm path
      run: |
        if (Test-Path "C:\InterSystems\Cache\bin\iristerm.exe") {
          Write-Host "iristerm.exe found"
        } else {
          Write-Host "iristerm.exe not found"
          exit 1
        }
      shell: pwsh

    - name: Add iristerm to PATH and run iristerm
      run: |
        $env:PATH += ";C:\InterSystems\Cache\bin"
        & "C:\InterSystems\Cache\bin\iristerm.exe"
      shell: pwsh

    - name: Display environment variables
      run: |
        Get-ChildItem Env:
      shell: pwsh

    - name: Check permissions
      run: |
        icacls "C:\InterSystems\Cache\bin\iristerm.exe"
      shell: cmd