name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: dir C:\InterSystems\Cache\bin
      shell: cmd

    - name: Verify iristerm path
      run: |
        if (Test-Path "C:\InterSystems\Cache\bin\iristerm.exe") {
          Write-Host "iristerm.exe found"
        } else {
          Write-Host "iristerm.exe not found"
          exit 1
        }
      shell: pwsh

    - name: Add iristerm to PATH and run iristerm
      run: |
        $env:PATH += ";C:\InterSystems\Cache\bin"
        & "C:\InterSystems\Cache\bin\iristerm.exe"
      shell: pwsh