name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add iristerm to PATH and run iristerm
      run: |
       c:\InterSystems\Cache\bin\iristerm
      shell: pwsh