on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Spécifie ici le runner auto-hébergé
    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v2   

      - name: Afficher le répertoire courant et définir une variable d'environnement
        run: |
          echo Current directory is: %cd%
          echo CURRENT_DIR=%cd% >> $GITHUB_ENV
        shell: cmd  

      - name: Lister les fichiers dans le répertoire courant
        run: dir %cd%
        shell: cmd

      - name: Vérifier que IRISimport.scr existe
        run: |
          if exist %cd%\IRISimport.scr (
            echo IRISimport.scr Est bien présent
            exit /b 0
          ) else (
            echo Le fichier IRISimport.scr n'existe pas
            exit /b 1
          )
        shell: cmd

      - name: Journaliser et exécuter le script iristerm IMPORT
        run: |
          set CURRENT_DIR=%cd%
          set COMMAND=C:\InterSystems\Cache\bin\iristerm.exe /console=cn_iptcp:127.0.0.1[23] %CURRENT_DIR%\IRISimport.scr
          echo %COMMAND%
          call %COMMAND% > output.log 2>&1
          type output.log
        shell: cmd
      - name: Lister les fichiers supprimés
        run: |
          git diff --name-only --diff-filter=D HEAD@{1} > deleted_files.log
          type deleted_files.log
        shell: cmd
      - name: Les des fichiers supprimés
        run: |
          $CURRENT_DIR = (Get-Location).Path
          Write-Host "Current Directory: $CURRENT_DIR"
          $filePath = "deleted_files.log"
          $uri = "http://10.10.1.27:57772/rest/Workflow/Delete"
          $headers = @{
            "Content-Type" = "text/plain"
            "DIRECTORY_ENV" = $CURRENT_DIR
          }
          Write-Host "Headers: $headers"
          $response = Invoke-WebRequest -Uri $uri -Method Post -InFile $filePath -Headers $headers
          Write-Host "Status Code: " $response.StatusCode
          if ($response.StatusCode -ne 200) {
              Write-Host "Request failed with status code $statusCode"
              exit 0
          }
          echo $response.Content 
      - name: Lister les fichiers ajoutés ou modifiés
        run: |
          git diff --name-only --diff-filter=AM HEAD@{1} > added_or_modified_files.log
          type added_or_modified_files.log
        shell: cmd
      - name: Les des fichiers modifier/ajouter
        run: |
          $CURRENT_DIR = (Get-Location).Path
          Write-Host "Current Directory: $CURRENT_DIR"
          $filePath = "added_or_modified_files.log"
          $uri = "http://10.10.1.27:57772/rest/Workflow/Compile"
          $headers = @{
            "Content-Type" = "text/plain"
            "DIRECTORY_ENV" = $CURRENT_DIR
          }
          Write-Host "Headers: $headers"
          $response = Invoke-WebRequest -Uri $uri -Method Post -InFile $filePath -Headers $headers
          Write-Host "Status Code: " $response.StatusCode
          if ($response.StatusCode -ne 200) {
              Write-Host "Request failed with status code $statusCode"
              exit 0
          }
          echo $response.Content  
           
        shell: powershell